language: python
python:
  - "2.7"
  - "3.5"
install: 
  - pip install -r requirements-test.txt
script: 
  - ./manage.py check
  - coverage run --source=. ./manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
