# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dluhy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministr',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='strana',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
